# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61e827792a3f769b0428a2929ec078d642a854d689e4222c0a5779bbbc67b78405fc3fecf8a264d2eea3f0f7e43ebf18ca0c8e6dadfd45a9ee5d065ff797d5f5

test:
  secret_key_base: e45414093bb986d8e6f5be93e0c9e614f254d1acf11b2c7b494b6963686026893fae6e3a52d74b26032f492e55d12adffe92b767e338e03bf4b2d1e644399517

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
